# Generated by Django 2.1.2 on 2018-10-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('screen_size', models.FloatField()),
                ('resolution_x', models.IntegerField()),
                ('resolution_y', models.IntegerField()),
                ('weight', models.FloatField()),
                ('cpu', models.CharField(max_length=40)),
                ('gpu', models.CharField(max_length=40)),
                ('ram', models.IntegerField()),
            ],
        ),
    ]
