# Generated by Django 2.1.2 on 2018-11-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='camera_rate',
            field=models.IntegerField(default=5),
        ),
    ]
