# Generated by Django 2.1.2 on 2018-11-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_smartphone_camera_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='fit',
            field=models.IntegerField(default=0),
        ),
    ]
