# Generated by Django 2.1.2 on 2018-11-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_smartphone_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='system',
            field=models.CharField(default='android', max_length=8),
        ),
    ]
