# Generated by Django 2.1.2 on 2018-11-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_smartphone_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='size',
            field=models.CharField(default='medium', max_length=7),
        ),
    ]
