# Generated by Django 2.1.2 on 2018-11-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_smartphone_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='battery_rate',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='display_rate',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='efficient_rate',
            field=models.IntegerField(default=5),
        ),
    ]
