# Generated by Django 2.1.2 on 2018-11-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_smartphone_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='image_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
