# Generated by Django 2.1.2 on 2018-11-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20181105_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
