# Generated by Django 2.1.2 on 2018-11-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0010_auto_20181109_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='is_jack',
            field=models.CharField(default='Yes', max_length=15),
        ),
    ]
