# Generated by Django 2.1.2 on 2018-11-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0011_smartphone_is_jack'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='battery',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
