# Generated by Django 2.1.2 on 2018-11-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0012_smartphone_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='memory',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
