# Generated by Django 2.1.2 on 2018-11-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0014_auto_20181109_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='cpu',
            field=models.CharField(max_length=100),
        ),
    ]
