# Generated by Django 2.1.2 on 2018-11-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0015_auto_20181109_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='dimensions',
            field=models.CharField(default='', max_length=30),
        ),
    ]
