# Generated by Django 2.1.2 on 2018-11-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0016_smartphone_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='battery_rate',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_rate',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='display_rate',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='efficient_rate',
            field=models.FloatField(default=5),
        ),
    ]
